server:
  port: ${LOCAL_SERVER_PORT}
# DB config
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_MYSQL_HOST}:${LOCAL_MYSQL_PORT}/${LOCAL_MYSQL_DB_NAME}?serverTimezone=Asia/Seoul
    username: ${LOCAL_MYSQL_NAME}
    password: ${LOCAL_MYSQL_PASSWORD}
  # DB update
  jpa:
    hibernate:
      ddl-auto: update
    # sql
    properties:
      hibernate:
        show_sql: true
        format_sql: true