server:
  port: ${PRODUCTION_SERVER_PORT}
# DB config
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PRODUCTION_MYSQL_HOST}:${PRODUCTION_MYSQL_PORT}/${PRODUCTION_MYSQL_DB_NAME}?serverTimezone=Asia/Seoul
    username: ${PRODUCTION_MYSQL_NAME}
    password: ${PRODUCTION_MYSQL_PASSWORD}
  # DB update
  jpa:
    hibernate:
      ddl-auto: update
    # sql
    properties:
      hibernate:
        show_sql: true
        format_sql: true